name: DEV Build and Deploy to Vultr
on:
  push:
    branches: [ ops ]

env:
  DEPLOYMENT_NAME: bills-service
  REPO_NAME: paymax2022
  PROJECT_NAME: paymax
  IMAGE: ghcr.io/paymax2022/bills-service
  ENVIRONMENT: dev

jobs:
  build-deploy:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Create Secrets
        run: |-
          mkdir -p /home/runner/.kube/
          echo "KUBECONFIG=${{ secrets.KUBECONFIG}}" > /home/runner/.kube/config
          cat /home/runner/.kube/config
